var navigation_bar_lists=
      [
        [{
          category:'二手车',
          icon_type :'che',
          color:'#0DC62A',
          fontsize:'40rpx',
          src:'../detail/second_hand_car/index'
        },{
          category:'严选车',
          icon_type :'mai',
          color:'#6671ED',
          fontsize:'60rpx',
          src:'../detail/strict_car/index'
        },{
          category:'免费卖车',
          icon_type:'qiandai',
          color:'#13DDB2',
          fontsize:'40rpx',
          src:'../detail/sale_car/index'
        },{
          category:"快速卖车",
          icon_type:"mai1",
          color:'#FFA441',
          fontsize:'30rpx',
          src:'../detail/fast_sale_car/index'
        },{
          category:"估价",
          icon_type:"maichegujiapsd01",
          color:'#F75B5B',
          fontsize:'40rpx',
          src:'../detail/valuation/index'
        },{
          category:"查成交",
          icon_type:"chengjiao",
          color:'#2A92ED',
          fontsize:'40rpx',
          src:'../detail/deal/index'
        },{
          category:"准新车",
          icon_type:"haopingwuxing",
          color:'#F65655',
          fontsize:'40rpx',
          src:'../detail/new_car/index'
        },{
          category:"降价急售",
          icon_type:"shandian",
          color:'#FFCF43',
          fontsize:'40rpx',
          src:'../detail/cheap_car/index'
        }
      ]
      ,[
        {
          category:"今日超值",
          icon_type:"fire",
          color:'#FC781B',
          fontsize:'40rpx',
          src:'../detail/today_great/index'
        },{
          category:"练手车",
          icon_type:"quxuechelian",
          color:'#0CC129',
          fontsize:'38rpx',
          src:'../detail/test_car/index'
        },{
          category:"热销排行",
          icon_type:"guest-branch",
          color:'#FFA23E',
          fontsize:'40rpx' ,
          src:'../detail/top/index'
        },{
          category:"百科",
          icon_type:"baike-tianchong",
          color:'#3194EF',
          fontsize:'40rpx',
          src:'../detail/knowledge/index'
        }
      ]
    ]
    module.exports = navigation_bar_lists;