var classify=[
    {type:'5万以下',
     hasIcon:false,
     icon:''
  },
  {type:'5-10万',
  hasIcon:false,
  icon:''
  }, {type:'10-15万',
  hasIcon:false,
  icon:''
  },{type:'15万以上',
  hasIcon:false,
  icon:''
  },{type:'大众',
  hasIcon:true,
  icon:'../../images/dazhong.png'
  },{type:'日产',
  hasIcon:true,
  icon:'../../images/richan.png'
  },{type:'现代',
  hasIcon:true,
  icon:'../../images/xiandai.png'
  },{type:'吉利',
  hasIcon:true,
  icon:'../../images/jili.png'
  },{type:'别克',
  hasIcon:true,
  icon:'../../images/bieke.jpg'
  },{type:'雪佛兰',
  hasIcon:true,
  icon:'../../images/xuefulan.png'
  },{type:'丰田',
  hasIcon:true,
  icon:'../../images/fengtian.png'
  },{type:'更多',
  hasIcon:true,
  icon:'../../images/more.png'
  }]
  module.exports = classify